name: pycnomobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  get: ^4.5.0
  get_storage: ^2.0.3
  http: ^0.13.0
  flutter_blue:
    git:
      url: https://github.com/boskokg/flutter_blue/
      ref: 0.12.0
  persistent_bottom_nav_bar: any
  font_awesome_flutter: 9.2.0
  auto_size_text: ^3.0.0
  fl_chart: ^0.41.0
  intl: ^0.17.0
  device_info_plus: ^3.2.1
  flutter_easyloading: ^3.0.3
  badges: ^2.0.2
  async: ^2.8.2
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_keyboard_visibility: ^5.1.1
  page_view_indicators: ^2.0.0
  timeago: ^3.2.2
  json_theme: ^3.3.1
  hexcolor: ^2.0.6
  tab_indicator_styler: ^2.0.0
  chart_sparkline: ^1.0.10
  smooth_page_indicator: ^1.0.0+2
  flutter_launcher_icons: ^0.9.2
  double_back_to_close_app: ^2.1.0
  loading_indicator: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/pycno_logo.png
    - assets/images/welcome_page.jpg
    - assets/images/app_logo.png
    - assets/images/potatoes_in_space_greenhouse.jpg
    - assets/images/rov.jpg
    - assets/images/space.jpg
    - assets/images/vineyard.jpg
    - assets/images/water_treatment.jpg
    - assets/images/stock0.jpg



  fonts:
    - family: Nulshock
      fonts:
        - asset: fonts/nulshock.ttf

    - family: GothamRounded
      fonts:
        - asset: fonts/GothamRounded-Bold.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.png"